"use client";

import { useMemo } from "react";
import { ChartLineUp, CheckCircle, FlagCheckered, TrendDown } from "@phosphor-icons/react";
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { useAppData } from "@/components/data-provider";
import { DOMAINS } from "@/lib/domains";
import { dateKey, percent } from "@/lib/utils";

export default function StatsPage() {
  const { data } = useAppData();
  const correct = data.answers.filter((item) => item.correct).length;
  const days = useMemo(() => Array.from({ length: 14 }).map((_, index) => { const d = new Date(); d.setDate(d.getDate() - (13 - index)); const key = dateKey(d); const answers = data.answers.filter((item) => dateKey(new Date(item.answeredAt)) === key); return { day: `${d.getMonth() + 1}/${d.getDate()}`, count: answers.length, rate: percent(answers.filter((item) => item.correct).length, answers.length) }; }), [data.answers]);
  const domainStats = DOMAINS.map((domain) => { const answers = data.answers.filter((item) => item.domainId === domain.id); return { ...domain, count: answers.length, correct: answers.filter((item) => item.correct).length, rate: percent(answers.filter((item) => item.correct).length, answers.length) }; }).sort((a, b) => (a.count ? a.rate : 101) - (b.count ? b.rate : 101));
  return <div><p className="flex items-center gap-2 text-sm font-black text-[#2b70c9]"><ChartLineUp size={21} weight="fill" />LEARNING STATS</p><h1 className="mt-2 text-3xl font-black tracking-[-0.035em] sm:text-4xl">学习数据，不做虚荣指标</h1><p className="mt-3 font-semibold text-[#777]">用答题量、正确率和知识域差距判断下一步该练什么。</p>
    <div className="mt-7 grid gap-4 sm:grid-cols-3">{[{ icon: FlagCheckered, label: "累计答题", value: data.answers.length, color: "#1cb0f6", bg: "#e8f7ff" }, { icon: CheckCircle, label: "整体正确率", value: `${percent(correct, data.answers.length)}%`, color: "#58a700", bg: "#eefbdc" }, { icon: TrendDown, label: "待复习", value: data.reviews.filter((item) => new Date(item.due) <= new Date()).length, color: "#ff4b4b", bg: "#fff0f0" }].map(({ icon: Icon, label, value, color, bg }) => <div key={label} className="rounded-[1.5rem] p-5" style={{ backgroundColor: bg }}><Icon size={27} weight="duotone" style={{ color }} /><p className="mt-4 text-sm font-black text-[#777]">{label}</p><p className="mt-1 text-3xl font-black tabular-nums">{value}</p></div>)}</div>
    <div className="mt-6 grid gap-5 lg:grid-cols-[1.4fr_1fr]"><section className="rounded-[1.7rem] border-2 border-[#e8e8e3] bg-white p-5"><div><h2 className="text-lg font-black">近 14 天趋势</h2><p className="text-sm font-semibold text-[#999]">柱状心态：先保持练习，再看正确率</p></div><div className="mt-5 h-72"><ResponsiveContainer width="100%" height="100%"><LineChart data={days} margin={{ top: 8, right: 8, left: -24, bottom: 0 }}><CartesianGrid stroke="#ededE9" strokeDasharray="4 4" vertical={false} /><XAxis dataKey="day" tick={{ fill: "#999", fontSize: 11, fontWeight: 700 }} axisLine={false} tickLine={false} /><YAxis domain={[0, 100]} tick={{ fill: "#aaa", fontSize: 11 }} axisLine={false} tickLine={false} /><Tooltip contentStyle={{ borderRadius: 14, border: "2px solid #e8e8e3", fontWeight: 700 }} /><Line type="monotone" dataKey="rate" name="正确率" stroke="#58cc02" strokeWidth={4} dot={{ r: 3, fill: "#58cc02", strokeWidth: 0 }} /></LineChart></ResponsiveContainer></div></section><section className="rounded-[1.7rem] border-2 border-[#e8e8e3] bg-white p-5"><h2 className="text-lg font-black">薄弱域排序</h2><p className="text-sm font-semibold text-[#999]">按已答题目的正确率从低到高</p><div className="mt-5 space-y-4">{domainStats.map((domain) => <div key={domain.id}><div className="flex items-center gap-2 text-sm"><span className="grid size-7 place-items-center rounded-lg text-xs font-black" style={{ backgroundColor: domain.softColor, color: domain.color }}>D{domain.number}</span><span className="font-bold">{domain.shortName}</span><span className="ml-auto font-black tabular-nums" style={{ color: domain.count ? domain.color : "#aaa" }}>{domain.count ? `${domain.rate}%` : "未练习"}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-[#eeeeea]"><div className="h-full rounded-full" style={{ width: `${domain.rate}%`, backgroundColor: domain.color }} /></div></div>)}</div></section></div>
    <section className="mt-5 rounded-[1.7rem] border-2 border-[#e8e8e3] bg-white p-5"><h2 className="text-lg font-black">模考记录</h2>{data.exams.length ? <div className="mt-4 overflow-x-auto"><table className="w-full min-w-lg text-left text-sm"><thead className="text-[#999]"><tr><th className="pb-3 font-black">日期</th><th className="pb-3 font-black">题量</th><th className="pb-3 font-black">用时</th><th className="pb-3 font-black">得分</th></tr></thead><tbody>{[...data.exams].reverse().map((exam) => <tr key={exam.id} className="border-t-2 border-[#f1f1ed]"><td className="py-3 font-bold">{new Date(exam.finishedAt).toLocaleDateString("zh-CN")}</td><td className="py-3 font-bold tabular-nums">{exam.questionIds.length}</td><td className="py-3 font-bold tabular-nums">{Math.round(exam.durationSeconds / 60)} 分钟</td><td className="py-3 text-lg font-black tabular-nums text-[#58a700]">{exam.score}%</td></tr>)}</tbody></table></div> : <p className="mt-4 rounded-xl bg-[#f5f5f1] p-5 text-center font-semibold text-[#888]">完成一场模考后，成绩会出现在这里。</p>}</section>
  </div>;
}
