"use client";

import { useMemo, useState } from "react";
import { ChartLineUp, CheckCircle, FlagCheckered, TrendDown } from "@phosphor-icons/react";
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { useAppData } from "@/components/data-provider";
import { chartColors } from "@/lib/chart-colors";
import { useIsDark } from "@/lib/use-theme";
import { BankSelector } from "@/components/bank-controls";
import { DOMAINS } from "@/lib/domains";
import { questionBankId } from "@/lib/question-banks";
import { dateKey, percent } from "@/lib/utils";
import type { BankId } from "@/lib/types";

export default function StatsPage() {
  const { data } = useAppData();
  const chart = chartColors(useIsDark());
  const [bankId, setBankId] = useState<BankId | "all">("all");
  const answers = data.answers.filter((item) => bankId === "all" || item.bankId === bankId);
  const exams = data.exams.filter((item) => bankId === "all" || item.bankId === bankId);
  const correct = answers.filter((item) => item.correct).length;
  const due = data.reviews.filter((item) => { if (item.targetType !== "question") return bankId === "all" && new Date(item.due) <= new Date(); const question = data.questions.find((candidate) => candidate.id === item.targetId); return new Date(item.due) <= new Date() && Boolean(question) && (bankId === "all" || questionBankId(question!) === bankId); }).length;
  const days = useMemo(() => Array.from({ length: 14 }).map((_, index) => { const d = new Date(); d.setDate(d.getDate() - (13 - index)); const key = dateKey(d); const daily = answers.filter((item) => dateKey(new Date(item.answeredAt)) === key); return { day: `${d.getMonth() + 1}/${d.getDate()}`, count: daily.length, rate: percent(daily.filter((item) => item.correct).length, daily.length) }; }), [answers]);
  const domainStats = DOMAINS.map((domain) => { const subset = answers.filter((item) => item.domainId === domain.id); return { ...domain, count: subset.length, correct: subset.filter((item) => item.correct).length, rate: percent(subset.filter((item) => item.correct).length, subset.length) }; }).sort((a, b) => (a.count ? a.rate : 101) - (b.count ? b.rate : 101));
  const mixed = answers.filter((item) => !item.domainId);
  const questionReviews = data.reviews.filter((item) => item.targetType === "question" && answers.some((answer) => answer.questionId === item.targetId));
  const mistakeStats = (["概念盲区", "审题失误", "混淆考点"] as const).map((type) => ({ type, count: questionReviews.filter((item) => item.mistakeType === type).length }));
  return <div><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="flex items-center gap-2 text-sm font-black text-[var(--c-2b70c9)]"><ChartLineUp size={21} weight="fill" />LEARNING STATS</p><h1 className="mt-2 text-3xl font-black tracking-[-0.035em] sm:text-4xl">学习数据，不做虚荣指标</h1><p className="mt-3 font-semibold text-[var(--c-777)]">用答题量、正确率和知识域差距判断下一步该练什么。</p></div><BankSelector value={bankId} onChange={setBankId} allowAll /></div>
    <div className="mt-7 grid gap-4 sm:grid-cols-3">{[{ icon: FlagCheckered, label: "累计答题", value: answers.length, color: "var(--c-1cb0f6)", bg: "var(--c-e8f7ff)" }, { icon: CheckCircle, label: "整体正确率", value: `${percent(correct, answers.length)}%`, color: "var(--c-58a700)", bg: "var(--c-eefbdc)" }, { icon: TrendDown, label: "待复习项目", value: due, color: "var(--c-ff4b4b)", bg: "var(--c-fff0f0)" }].map(({ icon: Icon, label, value, color, bg }) => <div key={label} className="rounded-[1.5rem] p-5" style={{ backgroundColor: bg }}><Icon size={27} weight="duotone" style={{ color }} /><p className="mt-4 text-sm font-black text-[var(--c-777)]">{label}</p><p className="mt-1 text-3xl font-black tabular-nums">{value}</p></div>)}</div>
    <div className="mt-6 grid gap-5 lg:grid-cols-[1.4fr_1fr]"><section className="rounded-[1.7rem] border-2 border-[var(--c-e8e8e3)] bg-[var(--surface)] p-5"><div><h2 className="text-lg font-black">近 14 天趋势</h2><p className="text-sm font-semibold text-[var(--c-999)]">柱状心态：先保持练习，再看正确率</p></div><div className="mt-5 h-72"><ResponsiveContainer width="100%" height="100%"><LineChart data={days} margin={{ top: 8, right: 8, left: -24, bottom: 0 }}><CartesianGrid stroke={chart.grid} strokeDasharray="4 4" vertical={false} /><XAxis dataKey="day" tick={{ fill: chart.axisTick, fontSize: 11, fontWeight: 700 }} axisLine={false} tickLine={false} /><YAxis domain={[0, 100]} tick={{ fill: chart.axisTickDim, fontSize: 11 }} axisLine={false} tickLine={false} /><Tooltip contentStyle={chart.tooltip} /><Line type="monotone" dataKey="rate" name="正确率" stroke={chart.accent} strokeWidth={4} dot={{ r: 3, fill: chart.accent, strokeWidth: 0 }} /></LineChart></ResponsiveContainer></div></section><section className="rounded-[1.7rem] border-2 border-[var(--c-e8e8e3)] bg-[var(--surface)] p-5"><h2 className="text-lg font-black">薄弱域排序</h2><p className="text-sm font-semibold text-[var(--c-999)]">按已答题目的正确率从低到高</p><div className="mt-5 space-y-4">{domainStats.map((domain) => <div key={domain.id}><div className="flex items-center gap-2 text-sm"><span className="grid size-7 place-items-center rounded-lg text-xs font-black" style={{ backgroundColor: domain.softColor, color: domain.color }}>D{domain.number}</span><span className="font-bold">{domain.shortName}</span><span className="ml-auto font-black tabular-nums" style={{ color: domain.count ? domain.color : "var(--c-aaa)" }}>{domain.count ? `${domain.rate}%` : "未练习"}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-[var(--c-eeeeea)]"><div className="h-full rounded-full" style={{ width: `${domain.rate}%`, backgroundColor: domain.color }} /></div></div>)}</div></section></div>
    {mixed.length > 0 && <section className="mt-5 rounded-[1.7rem] bg-[var(--c-e8f7ff)] p-5"><h2 className="font-black text-[var(--c-168fc7)]">综合模拟</h2><p className="mt-2 text-3xl font-black">{percent(mixed.filter((item) => item.correct).length, mixed.length)}%</p><p className="text-sm font-semibold text-[var(--c-667780)]">{mixed.length} 道未归入八域的综合模拟答题</p></section>}
    <section className="mt-5 rounded-[1.7rem] border-2 border-[var(--c-e8e8e3)] bg-[var(--surface)] p-5"><h2 className="text-lg font-black">错因分布</h2><p className="mt-1 text-sm font-semibold text-[var(--c-999)]">在题目解析后标记，帮助区分知识问题与审题问题。</p><div className="mt-4 grid gap-3 sm:grid-cols-3">{mistakeStats.map((item) => <div key={item.type} className="rounded-xl bg-[var(--c-f5f5f1)] p-4"><p className="text-sm font-bold text-[var(--c-777)]">{item.type}</p><p className="mt-1 text-2xl font-black">{item.count}</p></div>)}</div></section>
    <section className="mt-5 rounded-[1.7rem] border-2 border-[var(--c-e8e8e3)] bg-[var(--surface)] p-5"><h2 className="text-lg font-black">模考记录</h2>{exams.length ? <div className="mt-4 overflow-x-auto"><table className="w-full min-w-lg text-left text-sm"><thead className="text-[var(--c-999)]"><tr><th className="pb-3 font-black">日期</th><th className="pb-3 font-black">题量</th><th className="pb-3 font-black">用时</th><th className="pb-3 font-black">得分</th></tr></thead><tbody>{[...exams].reverse().map((exam) => <tr key={exam.id} className="border-t-2 border-[var(--c-f1f1ed)]"><td className="py-3 font-bold">{new Date(exam.finishedAt).toLocaleDateString("zh-CN")}</td><td className="py-3 font-bold tabular-nums">{exam.questionIds.length}</td><td className="py-3 font-bold tabular-nums">{Math.round(exam.durationSeconds / 60)} 分钟</td><td className="py-3 text-lg font-black tabular-nums text-[var(--c-58a700)]">{exam.score}%</td></tr>)}</tbody></table></div> : <p className="mt-4 rounded-xl bg-[var(--c-f5f5f1)] p-5 text-center font-semibold text-[var(--c-888)]">完成一场模考后，成绩会出现在这里。</p>}</section>
  </div>;
}
