"use client";

import { useEffect, useRef, useState } from "react";
import { Database, DownloadSimple, Eye, EyeSlash, FileArrowUp, Key, Trash } from "@phosphor-icons/react";
import { useAppData } from "@/components/data-provider";
import { Button } from "@/components/ui/button";

export default function SettingsPage() {
  const { data, hydrated, setAI, exportData, importData, reset } = useAppData();
  const [settings, setSettings] = useState(data.ai);
  const [showKey, setShowKey] = useState(false);
  const [notice, setNotice] = useState("");
  const [confirmReset, setConfirmReset] = useState(false);
  const fileRef = useRef<HTMLInputElement>(null);
  useEffect(() => { if (hydrated) setSettings(data.ai); }, [data.ai, hydrated]);
  const save = () => { setAI(settings); setNotice("AI 接口配置已保存到此浏览器"); };
  const importBackup = async (file?: File) => { if (!file) return; const result = importData(await file.text()); setNotice(result.message); if (fileRef.current) fileRef.current.value = ""; };
  return <div className="mx-auto max-w-3xl"><p className="text-sm font-black text-[#777]">SETTINGS</p><h1 className="mt-2 text-3xl font-black tracking-[-0.035em] sm:text-4xl">设置与本地数据</h1><p className="mt-2 font-semibold text-[#777]">所有设置和学习记录仅保存在当前浏览器，不会上传到 SALINGO 服务器。</p>
    {notice && <p className="mt-5 rounded-xl bg-[#edfadd] p-3 text-sm font-bold text-[#4c8c17]">{notice}</p>}
    <section className="mt-7 rounded-[1.7rem] border-2 border-[#e8e8e3] bg-white p-6"><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-2xl bg-[#e8f7ff] text-[#1cb0f6]"><Key size={24} weight="duotone" /></span><div><h2 className="text-lg font-black">AI 接口</h2><p className="text-sm font-semibold text-[#888]">支持 OpenAI Chat Completions 兼容端点</p></div></div><div className="mt-6 grid gap-4"><label className="text-sm font-black">接口地址<input value={settings.baseUrl} onChange={(e) => setSettings({ ...settings, baseUrl: e.target.value })} placeholder="https://api.openai.com/v1" className="mt-2 h-12 w-full rounded-xl border-2 border-[#deded8] px-4 outline-none focus:border-[#1cb0f6]" /></label><label className="text-sm font-black">API Key<span className="relative mt-2 block"><input type={showKey ? "text" : "password"} value={settings.apiKey} onChange={(e) => setSettings({ ...settings, apiKey: e.target.value })} placeholder="sk-…" className="h-12 w-full rounded-xl border-2 border-[#deded8] px-4 pr-12 outline-none focus:border-[#1cb0f6]" /><button type="button" onClick={() => setShowKey((value) => !value)} className="absolute right-2 top-1 grid size-10 place-items-center rounded-lg text-[#888] hover:bg-[#eee]" aria-label={showKey ? "隐藏密钥" : "显示密钥"}>{showKey ? <EyeSlash size={20} /> : <Eye size={20} />}</button></span></label><label className="text-sm font-black">模型名称<input value={settings.model} onChange={(e) => setSettings({ ...settings, model: e.target.value })} placeholder="gpt-5-mini" className="mt-2 h-12 w-full rounded-xl border-2 border-[#deded8] px-4 outline-none focus:border-[#1cb0f6]" /></label></div><p className="mt-4 rounded-xl bg-[#fff7e5] p-3 text-xs font-semibold leading-5 text-[#89672c]">安全提示：纯前端直连意味着 Key 对本机浏览器可见。请使用独立、限额、可随时撤销的 Key，不要在共享设备使用。</p><Button variant="blue" className="mt-5" onClick={save}>保存 AI 配置</Button></section>
    <section className="mt-5 rounded-[1.7rem] border-2 border-[#e8e8e3] bg-white p-6"><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-2xl bg-[#f3eee8] text-[#9b6b43]"><Database size={24} weight="duotone" /></span><div><h2 className="text-lg font-black">学习数据</h2><p className="text-sm font-semibold text-[#888]">{data.questions.length} 道题 · {data.answers.length} 条答题记录 · {data.exams.length} 场模考</p></div></div><div className="mt-6 flex flex-wrap gap-3"><Button variant="secondary" onClick={exportData}><DownloadSimple size={19} weight="bold" />导出完整备份</Button><input ref={fileRef} type="file" accept="application/json" className="hidden" onChange={(e) => importBackup(e.target.files?.[0])} /><Button variant="secondary" onClick={() => fileRef.current?.click()}><FileArrowUp size={19} weight="bold" />恢复备份</Button></div><div className="mt-6 border-t-2 border-[#f0f0ec] pt-6"><h3 className="font-black text-[#d83a3a]">危险操作</h3>{confirmReset ? <div className="mt-3 rounded-xl bg-[#fff0f0] p-4"><p className="text-sm font-bold text-[#a73b3b]">确定清除所有学习进度、错题、模考和自定义题目吗？此操作无法撤销。</p><div className="mt-3 flex gap-2"><Button variant="danger" onClick={() => { reset(); setConfirmReset(false); setNotice("本地数据已重置"); }}>确认清除</Button><Button variant="secondary" onClick={() => setConfirmReset(false)}>取消</Button></div></div> : <Button variant="ghost" className="mt-2 text-[#d83a3a]" onClick={() => setConfirmReset(true)}><Trash size={19} weight="bold" />重置全部本地数据</Button>}</div></section>
  </div>;
}
